name: Assign Reviewers by Branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewers based on base branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const branch = context.payload.pull_request.base.ref;
            let reviewers = [];

            if (branch === 'store') {
              reviewers = ['minsss0726', 'window101', 'parkeunhyo'];
            } else if (branch === 'users') {
              reviewers = ['minsss0726', 'gaaaani', 'sunJ0120'];
            } else if (branch === 'dev') {
              reviewers = ['minsss0726', 'window101', 'parkeunhyo', 'gaaaani', 'sunJ0120'];
            }

            if (reviewers.length > 0) {
              try {
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                  reviewers: reviewers
                });
                console.log('Reviewers assigned successfully');
              } catch (error) {
                console.log('Error assigning reviewers:', error);
              }
            } else {
              console.log('No reviewers assigned for branch:', branch);
            }